version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=example
      - ES_PORT=127.0.0.1:9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    ports:
      - "5601:5601"
    environment:
      - KIBANA_PASSWORD=example
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  demo:
    build: .
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200
